"""
app/excel/builder.py  —  openpyxl Excel workbook generation
Produces a multi-tab workbook from BOM validation data.
"""
import os
import uuid
from datetime import datetime
from typing import Optional
import openpyxl
from openpyxl.styles import (Font, PatternFill, Alignment,
                              Border, Side, numbers)
from openpyxl.utils import get_column_letter
from config import settings

# Colours
BLUE_DARK   = "1A3A6E"
BLUE_MID    = "2563C7"
BLUE_LIGHT  = "DBEAFE"
GREEN_LIGHT = "DCFCE7"
RED_LIGHT   = "FEE2E2"
YELLOW_LIGHT= "FEF9C3"
GREY_LIGHT  = "F1F5F9"
WHITE       = "FFFFFF"


def _hdr(ws, row: int, col: int, value, bold=True, bg=BLUE_DARK, fg=WHITE, wrap=False):
    cell = ws.cell(row=row, column=col, value=value)
    cell.font      = Font(bold=bold, color=fg, size=10)
    cell.fill      = PatternFill("solid", fgColor=bg)
    cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=wrap)
    return cell


def _cell(ws, row, col, value, bg=None, bold=False, fmt=None):
    cell = ws.cell(row=row, column=col, value=value)
    cell.font      = Font(bold=bold, size=10)
    cell.alignment = Alignment(vertical="center", wrap_text=False)
    if bg:
        cell.fill  = PatternFill("solid", fgColor=bg)
    if fmt:
        cell.number_format = fmt
    return cell


def _auto_width(ws):
    for col in ws.columns:
        max_len = 0
        col_letter = get_column_letter(col[0].column)
        for cell in col:
            if cell.value:
                max_len = max(max_len, len(str(cell.value)))
        ws.column_dimensions[col_letter].width = min(max(max_len + 2, 10), 50)


def _thin_border():
    side = Side(style="thin", color="CBD5E1")
    return Border(left=side, right=side, top=side, bottom=side)


# ─────────────────────────────────────────────────────────────────────────────
def build_validation_report(
    bom_header: dict,
    bom_lines:  list,
    cost_summary: dict,
    children:   list,
    components: list,
    suppliers:  list,
    validation_payload: dict,
    username:   str = "analyst",
    prompt:     str = "",
) -> str:
    """
    Build a multi-tab Excel workbook and return the file path.
    Tabs: Summary | BOM Lines | Compliance Issues | Supplier Risks | Components | Suppliers
    """
    wb = openpyxl.Workbook()
    wb.remove(wb.active)   # remove default sheet

    # ── Tab 1: Summary ───────────────────────────────────────────────────
    ws = wb.create_sheet("Summary")
    ws.sheet_view.showGridLines = False
    ws.row_dimensions[1].height = 40

    # Title banner
    ws.merge_cells("A1:H1")
    title_cell = ws["A1"]
    title_cell.value     = "bomiq SDM — BOM Validation Report"
    title_cell.font      = Font(bold=True, size=16, color=WHITE)
    title_cell.fill      = PatternFill("solid", fgColor=BLUE_DARK)
    title_cell.alignment = Alignment(horizontal="center", vertical="center")

    # Meta rows
    meta = [
        ("BOM Number",      bom_header.get("bomNumber", "—")),
        ("BOM Title",       bom_header.get("bomTitle",  "—")),
        ("Status",          bom_header.get("bomStatus", "—")),
        ("Revision",        bom_header.get("bomRevision", "—")),
        ("Product",         bom_header.get("productName", "—")),
        ("Generated By",    username),
        ("Generated At",    datetime.now().strftime("%Y-%m-%d %H:%M")),
        ("Prompt",          prompt[:200] if prompt else "—"),
    ]
    for i, (label, val) in enumerate(meta, start=3):
        ws.cell(row=i, column=1, value=label).font = Font(bold=True, size=10)
        ws.cell(row=i, column=2, value=val).font   = Font(size=10)

    # Cost summary box
    row = 13
    _hdr(ws, row, 1, "Cost Summary", bg=BLUE_MID, bold=True)
    _hdr(ws, row, 2, "Value",        bg=BLUE_MID, bold=True)
    cost_rows = [
        ("Total Material Cost", cost_summary.get("totalMaterialCost")),
        ("Total Labor Cost",    cost_summary.get("totalLaborCost")),
        ("Total Overhead Cost", cost_summary.get("totalOverheadCost")),
        ("Total BOM Cost",      cost_summary.get("totalBomCost")),
        ("Currency",            cost_summary.get("currencyCode", "USD")),
        ("Line Item Count",     cost_summary.get("lineItemCount", 0)),
    ]
    for i, (label, val) in enumerate(cost_rows, start=row+1):
        _cell(ws, i, 1, label, bg=GREY_LIGHT, bold=True)
        _cell(ws, i, 2, val)

    # Validation KPI box
    row = 21
    issues   = validation_payload.get("complianceIssues", [])
    sup_risks = validation_payload.get("supplierRisks", [])
    kpis = [
        ("Line Items",          validation_payload.get("lineItemCount", 0)),
        ("Compliance Issues",   len(issues)),
        ("Supplier Risks",      len(sup_risks)),
        ("Child BOMs",          len(children)),
    ]
    _hdr(ws, row, 1, "Validation KPIs", bg=BLUE_MID, bold=True)
    _hdr(ws, row, 2, "Count",           bg=BLUE_MID, bold=True)
    for i, (label, val) in enumerate(kpis, start=row+1):
        bg = RED_LIGHT if (label != "Line Items" and val > 0) else GREY_LIGHT
        _cell(ws, i, 1, label, bg=GREY_LIGHT, bold=True)
        _cell(ws, i, 2, val,   bg=bg)

    _auto_width(ws)

    # ── Tab 2: BOM Lines ─────────────────────────────────────────────────
    ws2 = wb.create_sheet("BOM Lines")
    ws2.sheet_view.showGridLines = False
    headers = ["Line #", "Part Number", "Description", "Qty", "UOM",
               "Unit Cost", "Ext Cost", "Lifecycle", "Ref Designators", "Critical"]
    for col, h in enumerate(headers, 1):
        _hdr(ws2, 1, col, h)
    for i, line in enumerate(bom_lines, start=2):
        comp = line.get("component", {}) or {}
        bg   = RED_LIGHT if comp.get("lifecycleStatus") in ("OBSOLETE", "NRND") else None
        _cell(ws2, i, 1,  line.get("lineNumber"),                   bg=bg)
        _cell(ws2, i, 2,  comp.get("partNumber", "—"),              bg=bg)
        _cell(ws2, i, 3,  comp.get("partDescription", "—"),         bg=bg)
        _cell(ws2, i, 4,  line.get("quantity"),                     bg=bg)
        _cell(ws2, i, 5,  line.get("uomCode", "EA"),                bg=bg)
        _cell(ws2, i, 6,  line.get("unitCostOverride") or comp.get("unitCost"), bg=bg, fmt='"$"#,##0.0000')
        _cell(ws2, i, 7,  line.get("extendedCost"),                 bg=bg, fmt='"$"#,##0.00')
        _cell(ws2, i, 8,  comp.get("lifecycleStatus", "—"),         bg=bg)
        _cell(ws2, i, 9,  line.get("referenceDesignators", ""),     bg=bg)
        _cell(ws2, i, 10, "YES" if line.get("criticalComponent") else "", bg=bg)
    _auto_width(ws2)

    # ── Tab 3: Compliance Issues ──────────────────────────────────────────
    ws3 = wb.create_sheet("Compliance Issues")
    ws3.sheet_view.showGridLines = False
    for col, h in enumerate(["Part Number", "Issue"], 1):
        _hdr(ws3, 1, col, h)
    if issues:
        for i, issue in enumerate(issues, start=2):
            _cell(ws3, i, 1, issue.get("partNumber", "—"), bg=RED_LIGHT)
            _cell(ws3, i, 2, issue.get("issue", "—"),      bg=RED_LIGHT)
    else:
        ws3.merge_cells("A2:B2")
        _cell(ws3, 2, 1, "✓ No compliance issues found", bg=GREEN_LIGHT, bold=True)
    _auto_width(ws3)

    # ── Tab 4: Supplier Risks ─────────────────────────────────────────────
    ws4 = wb.create_sheet("Supplier Risks")
    ws4.sheet_view.showGridLines = False
    for col, h in enumerate(["Supplier Code", "Risk Rating", "Component"], 1):
        _hdr(ws4, 1, col, h)
    if sup_risks:
        for i, risk in enumerate(sup_risks, start=2):
            _cell(ws4, i, 1, risk.get("supplierCode", "—"), bg=RED_LIGHT)
            _cell(ws4, i, 2, risk.get("risk", "—"),         bg=RED_LIGHT)
            _cell(ws4, i, 3, risk.get("component", "—"),    bg=RED_LIGHT)
    else:
        ws4.merge_cells("A2:C2")
        _cell(ws4, 2, 1, "✓ No high-risk suppliers found", bg=GREEN_LIGHT, bold=True)
    _auto_width(ws4)

    # ── Tab 5: All Components ─────────────────────────────────────────────
    ws5 = wb.create_sheet("Components")
    ws5.sheet_view.showGridLines = False
    comp_hdrs = ["Part Number", "Description", "Lifecycle", "Manufacturer",
                 "MPN", "Unit Cost", "RoHS", "Lead Time (days)"]
    for col, h in enumerate(comp_hdrs, 1):
        _hdr(ws5, 1, col, h)
    for i, c in enumerate(components, start=2):
        bg = RED_LIGHT if c.get("lifecycleStatus") in ("OBSOLETE", "NRND") else None
        _cell(ws5, i, 1, c.get("partNumber"),          bg=bg)
        _cell(ws5, i, 2, c.get("partDescription"),     bg=bg)
        _cell(ws5, i, 3, c.get("lifecycleStatus"),     bg=bg)
        _cell(ws5, i, 4, c.get("manufacturerName"),    bg=bg)
        _cell(ws5, i, 5, c.get("manufacturerPartNo"),  bg=bg)
        _cell(ws5, i, 6, c.get("unitCost"),            bg=bg, fmt='"$"#,##0.0000')
        _cell(ws5, i, 7, "Yes" if c.get("rohsCompliant") else "No", bg=bg)
        _cell(ws5, i, 8, c.get("shelfLifeDays"),       bg=bg)
    _auto_width(ws5)

    # ── Tab 6: Suppliers ──────────────────────────────────────────────────
    ws6 = wb.create_sheet("Suppliers")
    ws6.sheet_view.showGridLines = False
    sup_hdrs = ["Code", "Name", "Country", "Tier", "Lead Time (days)", "Currency"]
    for col, h in enumerate(sup_hdrs, 1):
        _hdr(ws6, 1, col, h)
    for i, s in enumerate(suppliers, start=2):
        _cell(ws6, i, 1, s.get("supplierCode"))
        _cell(ws6, i, 2, s.get("legalName"))
        _cell(ws6, i, 3, s.get("countryOfOrigin"))
        _cell(ws6, i, 4, s.get("supplierTier"))
        _cell(ws6, i, 5, s.get("leadTimeDays"))
        _cell(ws6, i, 6, s.get("currencyCode"))
    _auto_width(ws6)

    # Save
    filename  = f"bom_validation_{bom_header.get('bomNumber','unknown')}_{uuid.uuid4().hex[:8]}.xlsx"
    filepath  = os.path.join(settings.DOWNLOADS_DIR, filename)
    wb.save(filepath)
    return filepath


def build_component_report(components: list, title: str = "Component Report") -> str:
    """Simple single-tab component list report."""
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Components"
    ws.sheet_view.showGridLines = False

    ws.merge_cells("A1:H1")
    ws["A1"].value     = f"bomiq SDM — {title}"
    ws["A1"].font      = Font(bold=True, size=14, color=WHITE)
    ws["A1"].fill      = PatternFill("solid", fgColor=BLUE_DARK)
    ws["A1"].alignment = Alignment(horizontal="center", vertical="center")

    hdrs = ["Part Number", "Description", "Lifecycle", "Manufacturer",
            "MPN", "Unit Cost", "RoHS Compliant", "Lead Time (days)"]
    for col, h in enumerate(hdrs, 1):
        _hdr(ws, 2, col, h)
    for i, c in enumerate(components, start=3):
        bg = RED_LIGHT if c.get("lifecycleStatus") in ("OBSOLETE", "NRND") else None
        _cell(ws, i, 1, c.get("partNumber"),        bg=bg)
        _cell(ws, i, 2, c.get("partDescription"),   bg=bg)
        _cell(ws, i, 3, c.get("lifecycleStatus"),   bg=bg)
        _cell(ws, i, 4, c.get("manufacturerName"),  bg=bg)
        _cell(ws, i, 5, c.get("manufacturerPartNo"),bg=bg)
        _cell(ws, i, 6, c.get("unitCost"),          bg=bg, fmt='"$"#,##0.0000')
        _cell(ws, i, 7, "Yes" if c.get("rohsCompliant") else "No", bg=bg)
        _cell(ws, i, 8, c.get("shelfLifeDays"),     bg=bg)
    _auto_width(ws)

    filename = f"components_{uuid.uuid4().hex[:8]}.xlsx"
    filepath = os.path.join(settings.DOWNLOADS_DIR, filename)
    wb.save(filepath)
    return filepath


def build_supplier_report(suppliers: list) -> str:
    """Single-tab supplier report."""
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Suppliers"
    ws.sheet_view.showGridLines = False

    ws.merge_cells("A1:F1")
    ws["A1"].value     = "bomiq SDM — Supplier Registry Report"
    ws["A1"].font      = Font(bold=True, size=14, color=WHITE)
    ws["A1"].fill      = PatternFill("solid", fgColor=BLUE_DARK)
    ws["A1"].alignment = Alignment(horizontal="center", vertical="center")

    hdrs = ["Code", "Legal Name", "Country", "Tier", "Lead Time (days)", "Currency"]
    for col, h in enumerate(hdrs, 1):
        _hdr(ws, 2, col, h)
    for i, s in enumerate(suppliers, start=3):
        _cell(ws, i, 1, s.get("supplierCode"))
        _cell(ws, i, 2, s.get("legalName"))
        _cell(ws, i, 3, s.get("countryOfOrigin"))
        _cell(ws, i, 4, s.get("supplierTier"))
        _cell(ws, i, 5, s.get("leadTimeDays"))
        _cell(ws, i, 6, s.get("currencyCode"))
    _auto_width(ws)

    filename = f"suppliers_{uuid.uuid4().hex[:8]}.xlsx"
    filepath = os.path.join(settings.DOWNLOADS_DIR, filename)
    wb.save(filepath)
    return filepath
